### ISSUE TITLE
[1.8.8/9] Crash while running on a dedicated server

### ISSUE THREAD

**Issue by joekaiser** [joekaiser/practicalities#47]
```
net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: practicalities/items/ItemMagnet
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:162)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:551)
    at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:319)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:112)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: practicalities/items/ItemMagnet
    at practicalities.ProxyCommon.preInit(ProxyCommon.java:19)
    at practicalities.PracticalitiesMod.preInit(PracticalitiesMod.java:36)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
```

**Comment by joekaiser** [comment]
I am wondering if the person who reported this was using the deobf version

**Comment by joekaiser** [comment]
The cause is a derp I made. Each Item implements ItemMeshDefinition, which of course isn't on the server instance. Gotta refactor a lot
